name: OpenSoftware-World-YoutubeDownloader CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Download
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements.txt
        run: pip install -r requirements.txt

      - name: Test
        run: python -c "import ytdownloader"