name: Build & Release

on:
  push:
    tags:
      - "yt*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile ytdownloader.py

      - name: Create package
        run: zip -r ytdownloader.zip dist/

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ytdownloader.zip